### PR TITLE
Fig1 as pdf + tuning it

### PR DESCRIPTION
**Pull request by twitwi**
I made this PR on top of `gvwilson/for-submission` for my own convenience.

The core commit is https://github.com/swcarpentry/collaborative-lesson-development/commit/2dafe68acfd0216eec638c3aa538fa7f20fe621d

Which is a tentative improvements of fig1

- make it included as pdf so it is not pixelized/rasterized (generated with inkscape + ghostscript cleaning)
- use a font that is closer (in style and size) to the paper's font
- add some space to breathe
- add crossroad sign (openclipart)

### CODE REVIEW

**Comment by twitwi** [comment]
NB: the .png file is outdated, the paper uses the .pdf

**Comment by gvwilson** [comment]
There are *lot* of diffs now - is this worth rebasing?

**Comment by raynamharris** [comment]
@twitwi It looks like we both made changes to an older version of figure 1, so now your and my newest commits (https://github.com/swcarpentry/collaborative-lesson-development/pull/37) are in conflict. 

In this conflict, I add some white space and I changed the image for the link to other resources. I do really the like direction sign, but let me know if you like the hyperlink image, since now the working of the rule is "link to other resources" rather than "point to other resources".

**Comment by twitwi** [comment]
Sorry, I didn't know you worked on the figure. I'm closing this.

**Pull request closed without merging**
